# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: job1
  pool: Default
  displayName: "job1 - run"
  workspace:
    clean: all
  variables:
    testvar: "test var"
  cancelTimeoutInMinutes: 5
  steps:
    - checkout: self
      path: $(Build.SourcesDirectory)\mytestpath
    - script: echo Hello, world!
      displayName: 'Run a one-line script. Var: $(testvar)'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

    - task: InlinePowershell@1
      displayName: Get ENVs
      inputs:
        Script: 'Get-Item c:\pkg'

- job: 
  displayName: "job 2 - run"
  dependsOn: job1
  pool: Linux
  steps:
    - task: Bash@3
      displayName: Execute script
      inputs:
        targetType: inline
        script: echo "job2 script"
        
      
